### ISSUE TITLE
How's the project going?

### ISSUE THREAD

**Issue by GuiDevloper** [FadedCoder/YTSwag#2]
Hi @FadedCoder, I seen your extension on r/YoutubeMusic!

Before knowing your project I started an initiative of developing the multi-purpose extension [Browser UI Tools](https://github.com/GuiDevloper/browser-ui-tools). It was built with multi-sites and functions on mind.

After knowing your work I thought how awesome would be if in some way we joined!
I cloned this repo to study the code, then solved some Issues like:
- No need to reload on Lyrics Enable/Disable
- More reliable current video url getter
- Disabling previous PIP on opening a non-video

Then I still have the doubt, how could we join?
As my extension is multi-purpose, we could put functions from here to there.
As I cannot publish on Google Store, we could join here and publish on your account.

I'am here to help this project get to the next level, Let's Go!

**Comment by Yureien** [comment]
Hey @GuiDevloper! Your extension looks awesome, I had plans to implement features like that into YouTube Music myself, but I was a bit busy.

I think it's better if this repo just targets YouTube Music or other music players (though it's best if it's packaged separately). This is because people might not want all the tools inside a single extension, and instead use multiple extensions. But I'm not sure which would be better, different packages for each site under a common organization, or a single joint one.

About adding new features, can you create Pull Requests? I can make you a contributor on this repo too :)

Also, I don't check my GitHub very often so I might miss out on some conversations. Are you on Telegram or Discord or similar? We can chat more conveniently then.

**Comment by GuiDevloper** [comment]
Very thanks for the compliments, @FadedCoder!

The idea on that project was exactly be a "dynamic" extension, with the user enabling/disabling what he wants, avoiding the extension-spaghetti.

But trying to predict what users could prefer, I like the [Stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne) model, in this case we could offer a base extension (players changer) and have a Organization containing plugins which they can choose.
Ideas to take the world right here :grin:

Indeed, I was going to create PRs, just needed to know if you are okay with all this and organize/test more the code which I changed.
My Discord: `GuiDevloper#0520`
